apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: proxy
    spec:
      containers:
      - image: leanlabs/nginx:1.0.1
        name: proxy
        ports:
        - containerPort: 443
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: proxy-claim0
        - mountPath: /etc/nginx/certs
          name: proxy-claim1
        - mountPath: /etc/nginx/sites-enabled
          name: proxy-claim2
      restartPolicy: Always
      volumes:
      - name: proxy-claim0
        persistentVolumeClaim:
          claimName: proxy-claim0
      - name: proxy-claim1
        persistentVolumeClaim:
          claimName: proxy-claim1
      - name: proxy-claim2
        persistentVolumeClaim:
          claimName: proxy-claim2
status: {}
